pub const CHALLENGE_VALID_MINUTES: i64 = 15;
pub const POW_DIFFICULTY_BITS: i32 = 13;
pub const MINIMUM_ELAPSED_MS: i32 = 2_000;
pub const MAX_FAILED_ATTEMPTS: i32 = 5;
pub const CHALLENGE_ISSUE_LIMIT_PER_TOKEN: u32 = 8;
pub const CHALLENGE_ISSUE_LIMIT_PER_IP: u32 = 40;
pub const CHALLENGE_SUBMIT_LIMIT_PER_CHALLENGE: u32 = 10;
pub const RATE_WINDOW_SECONDS: u64 = 900;
