// autogenerated metadata - do not edit!
#[derive(Debug)]
pub struct LibVersion {
    pub name: &'static str,
    pub version: &'static str,
}

impl LibVersion {
    pub fn get_name(&self) -> &'static str {
        self.name
    }
    pub fn get_version(&self) -> &'static str {
        self.version
    }
}

pub struct LibVersionMap {
    pub list: &'static [LibVersion],
}

impl LibVersionMap {
    pub fn get(&self, name: &str) -> Option<&LibVersion> {
        self.list.iter().find(|v| v.get_name() == name)
    }
}

/// AUTO-GENERATED BY build.rs
pub const PROJECT_NAME: &str = "be";
pub const PROJECT_VERSION: &str = "0.1.0";
pub const BUILD_TIME_UTC: &str = "2026-04-28T00:16:44.938793150+00:00";
pub const RUSTC_VERSION: &str = "rustc 1.97.0-nightly (ca9a134e0 2026-04-26)";
pub const LIB_VERSIONS: [LibVersion; 17] = [
    LibVersion {
        name: "axum",
        version: "0.8.9",
    },
    LibVersion {
        name: "axum-server",
        version: "0.8.0",
    },
    LibVersion {
        name: "chrono",
        version: "0.4.44",
    },
    LibVersion {
        name: "dotenvy",
        version: "0.15.7",
    },
    LibVersion {
        name: "mimalloc",
        version: "0.1.50",
    },
    LibVersion {
        name: "mime_guess",
        version: "2.0.5",
    },
    LibVersion {
        name: "rust-embed",
        version: "8.11.0",
    },
    LibVersion {
        name: "rustls",
        version: "0.23.39",
    },
    LibVersion {
        name: "serde",
        version: "1.0.228",
    },
    LibVersion {
        name: "serde_json",
        version: "1.0.149",
    },
    LibVersion {
        name: "tokio",
        version: "1.52.1",
    },
    LibVersion {
        name: "tower-http",
        version: "0.6.8",
    },
    LibVersion {
        name: "tracing",
        version: "0.1.44",
    },
    LibVersion {
        name: "tracing-appender",
        version: "0.2.5",
    },
    LibVersion {
        name: "tracing-subscriber",
        version: "0.3.23",
    },
    LibVersion {
        name: "utoipa",
        version: "5.4.0",
    },
    LibVersion {
        name: "utoipa-swagger-ui",
        version: "9.0.2",
    },
];
pub const LIB_VERSION_MAP: LibVersionMap = LibVersionMap {
    list: &LIB_VERSIONS,
};
